GO
USE AgriculturalProperty

/* - Insertion in the table Service: AP_Service - */
INSERT INTO dbo.AP_Service(Name, Cost) VALUES('Trabajador', 1500)
INSERT INTO dbo.AP_Service(Name, Cost) VALUES('Ing. Agronomo', 8500)
INSERT INTO dbo.AP_Service(Name, Cost) VALUES('Ing. Agricola', 6500)
INSERT INTO dbo.AP_Service(Name, Cost) VALUES('Ing. Ambiental', 7500)
INSERT INTO dbo.AP_Service(Name, Cost) VALUES('Biotecnologo', 8500)
INSERT INTO dbo.AP_Service(Name, Cost) VALUES('Ing. Agronegocios', 3500)
INSERT INTO dbo.AP_Service(Name, Cost) VALUES('Ing. Forestal', 5400)
INSERT INTO dbo.AP_Service(Name, Cost) VALUES('Ing. Civil', 7500)
INSERT INTO dbo.AP_Service(Name, Cost) VALUES('Mecanico', 1500)
INSERT INTO dbo.AP_Service(Name, Cost) VALUES('Administrador de Negocios', 4500)
INSERT INTO dbo.AP_Service(Name, Cost) VALUES('Mantenimiento', 3600)
INSERT INTO dbo.AP_Service(Name, Cost) VALUES('Limpieza', 1500)


/* - Insertion in the table Supply: AP_Supply - */
INSERT INTO dbo.AP_Supply(Name, Cost) VALUES('Semillas de Maiz', 250)
INSERT INTO dbo.AP_Supply(Name, Cost) VALUES('Semillas de Trigo', 250)
INSERT INTO dbo.AP_Supply(Name, Cost) VALUES('Semillas de Soja', 250)
INSERT INTO dbo.AP_Supply(Name, Cost) VALUES('Semillas de Arroz', 250)
INSERT INTO dbo.AP_Supply(Name, Cost) VALUES('Semillas de Palma', 250)
INSERT INTO dbo.AP_Supply(Name, Cost) VALUES('Semillas de Frijol', 250)
INSERT INTO dbo.AP_Supply(Name, Cost) VALUES('Semillas de Tomate', 250)
INSERT INTO dbo.AP_Supply(Name, Cost) VALUES('Semillas de Chile', 250)
INSERT INTO dbo.AP_Supply(Name, Cost) VALUES('Fertilizante', 10000)
INSERT INTO dbo.AP_Supply(Name, Cost) VALUES('Abono', 7500)
INSERT INTO dbo.AP_Supply(Name, Cost) VALUES('Suplemento', 8500)
INSERT INTO dbo.AP_Supply(Name, Cost) VALUES('Fungicida', 9000)
INSERT INTO dbo.AP_Supply(Name, Cost) VALUES('Herbicida', 8500)
INSERT INTO dbo.AP_Supply(Name, Cost) VALUES('Pala', 3000)
INSERT INTO dbo.AP_Supply(Name, Cost) VALUES('Carretillo', 4500)
INSERT INTO dbo.AP_Supply(Name, Cost) VALUES('Palin', 3500)
INSERT INTO dbo.AP_Supply(Name, Cost) VALUES('Tornillos', 20)
INSERT INTO dbo.AP_Supply(Name, Cost) VALUES('Aceite', 1500)
INSERT INTO dbo.AP_Supply(Name, Cost) VALUES('Rastrillo', 4000)
INSERT INTO dbo.AP_Supply(Name, Cost) VALUES('Cedazo', 6500)
INSERT INTO dbo.AP_Supply(Name, Cost) VALUES('Plastico', 5500)
INSERT INTO dbo.AP_Supply(Name, Cost) VALUES('Bolsa jardinera', 100)
INSERT INTO dbo.AP_Supply(Name, Cost) VALUES('Frascos', 450)
INSERT INTO dbo.AP_Supply(Name, Cost) VALUES('Madera', 4000)
INSERT INTO dbo.AP_Supply(Name, Cost) VALUES('Tubos', 5000)
INSERT INTO dbo.AP_Supply(Name, Cost) VALUES('Manguera', 2500)
INSERT INTO dbo.AP_Supply(Name, Cost) VALUES('Clavos', 10)
INSERT INTO dbo.AP_Supply(Name, Cost) VALUES('Destornillador', 1500)

/* - Insertion in the table Machinery: AP_Machinery - */
INSERT INTO dbo.AP_Machinery(Name, Cost) VALUES('Chapulin', 1100)
INSERT INTO dbo.AP_Machinery(Name, Cost) VALUES('Arado', 1150)
INSERT INTO dbo.AP_Machinery(Name, Cost) VALUES('Cortadora', 1000)
INSERT INTO dbo.AP_Machinery(Name, Cost) VALUES('Cosechadora', 4000)
INSERT INTO dbo.AP_Machinery(Name, Cost) VALUES('Fumigadora', 2300)
INSERT INTO dbo.AP_Machinery(Name, Cost) VALUES('Tractor', 2250)
INSERT INTO dbo.AP_Machinery(Name, Cost) VALUES('Camion', 1500)
INSERT INTO dbo.AP_Machinery(Name, Cost) VALUES('Rociador', 1250)
INSERT INTO dbo.AP_Machinery(Name, Cost) VALUES('Bagoneta', 2000)
INSERT INTO dbo.AP_Machinery(Name, Cost) VALUES('Bulldozer', 3500)
INSERT INTO dbo.AP_Machinery(Name, Cost) VALUES('Podadora', 1250)
INSERT INTO dbo.AP_Machinery(Name, Cost) VALUES('Sierra', 750)
INSERT INTO dbo.AP_Machinery(Name, Cost) VALUES('Recolector', 2000)
INSERT INTO dbo.AP_Machinery(Name, Cost) VALUES('Bomba de agua', 1750)
INSERT INTO dbo.AP_Machinery(Name, Cost) VALUES('Cargador', 1500)