/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.sql.LotXCycle;

/**
 *
 * @author usuario
 */
public class JDlgModify extends javax.swing.JDialog {

    DefaultComboBoxModel modeltipoEvaluaciones;
    DefaultComboBoxModel tipoInstancia;
    private DefaultComboBoxModel modelLotXcyle;

    public String getLotCode() {
        return lotCode;
    }

    public void setLotCode(String lotCode) {
        this.lotCode = lotCode;
    }

    public String getCycleCode() {
        return cycleCode;
    }

    public void setCycleCode(String cycleCode) {
        this.cycleCode = cycleCode;
    }
    private String lotCode;
    private String cycleCode;

    public JDlgModify(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tipoInstancia = new DefaultComboBoxModel();
        this.tipoInstancia.addElement("");
        this.tipoInstancia.addElement("Fija");
        this.tipoInstancia.addElement("Variable");
        setIconImage(new ImageIcon(getClass().getResource("/view/source/favicon.ico")).getImage());
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno = new ImageIcon(this.getClass().getResource("/view/source/fondo.jpg"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight()); 
    }
    
    
    public void getDescrip() throws SQLException {
        this.modelLotXcyle = new DefaultComboBoxModel();
        this.modelLotXcyle.addElement("");
        ArrayList<String> lotsxcycle = LotXCycle.getInstance().getDescription(getLotCode(), getCycleCode());
        for (String lotxcycle : lotsxcycle) {
            this.modelLotXcyle.addElement(lotxcycle);
        }
        this.jCBDescription.setModel(modelLotXcyle);
    } 
    
    public void getActivityType() throws SQLException {
        this.modelLotXcyle = new DefaultComboBoxModel();
        this.modelLotXcyle.addElement("");
        ArrayList<String> lotsxcycle = LotXCycle.getInstance().getActivityType(1);
        for (String lotxcycle : lotsxcycle) {
            this.modelLotXcyle.addElement(lotxcycle);
        }
        this.jCBActivityType.setModel(modelLotXcyle);
    } 
    public void getRequetName() throws SQLException {
        this.modelLotXcyle = new DefaultComboBoxModel();
        this.modelLotXcyle.addElement("");
        ArrayList<String> lotsxcycle = LotXCycle.getInstance().getRequestName(jCBDescription.getSelectedItem().toString());
        for (String lotxcycle : lotsxcycle) {
            this.modelLotXcyle.addElement(lotxcycle);
        }
        this.jCBRequestName.setModel(modelLotXcyle);
    } 
    
    public boolean modifyRequest()throws SQLException {
        this.modelLotXcyle = new DefaultComboBoxModel();
        this.modelLotXcyle.addElement("");
        if (LotXCycle.getInstance().validatemodify(jCBDescription.getSelectedItem().toString(), jCBRequestName.getSelectedItem().toString() ,jCBActivityType.getSelectedItem().toString(), Float.parseFloat(jTextModAmount.getText()))){
            LotXCycle.getInstance().modifyRequest(jCBDescription.getSelectedItem().toString(), jCBRequestName.getSelectedItem().toString(),jCBActivityType.getSelectedItem().toString(), Float.parseFloat(jTextModAmount.getText()));
            System.out.println(jCBActivityType.getSelectedItem().toString());
            return true;
        }
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCBDescription = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextModAmount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBtnRegistrar = new javax.swing.JButton();
        jCBActivityType = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jCBRequestName = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jBtnLoad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modify");
        setResizable(false);

        jCBDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBDescriptionActionPerformed(evt);
            }
        });

        jLabel3.setText("Monto:");

        jTextModAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextModAmount.setText("0");

        jLabel5.setText("Descripcion:");

        jLabel1.setText("-----------------------------------Campos a modificar---------------------------");

        jBtnRegistrar.setText("Modificar");
        jBtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegistrarActionPerformed(evt);
            }
        });

        jCBActivityType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBActivityTypeActionPerformed(evt);
            }
        });

        jLabel7.setText("ActivityType:");

        jCBRequestName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBRequestNameActionPerformed(evt);
            }
        });

        jLabel8.setText("Request Name:");

        jBtnLoad.setText("Load");
        jBtnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCBActivityType, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jTextModAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel8)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCBRequestName, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(48, 48, 48)
                        .addComponent(jCBDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jBtnLoad)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBActivityType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextModAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBRequestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jBtnRegistrar)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegistrarActionPerformed
        try {

            if (modifyRequest()){
                JOptionPane.showMessageDialog(rootPane, "Cambio realizado");
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Faltan Datos o no existe una solicitud");
            }
        } catch (SQLException ex) {

            Logger.getLogger(JDlgApprove.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_jBtnRegistrarActionPerformed

    private void jCBDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBDescriptionActionPerformed

    private void jCBActivityTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBActivityTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBActivityTypeActionPerformed

    private void jCBRequestNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBRequestNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBRequestNameActionPerformed

    private void jBtnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLoadActionPerformed
        if (jCBDescription.getSelectedItem().toString().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Seleccione una opcion de descripcion");
        } else {
            try {
                this.getRequetName();
            } catch (SQLException ex) {
                Logger.getLogger(JDlgModify.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jBtnLoadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgModify dialog = new JDlgModify(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLoad;
    private javax.swing.JButton jBtnRegistrar;
    private javax.swing.JComboBox jCBActivityType;
    private javax.swing.JComboBox jCBDescription;
    private javax.swing.JComboBox jCBRequestName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextModAmount;
    // End of variables declaration//GEN-END:variables
}
