/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
 
package view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.sql.Cycle;
import model.sql.Lot;
import model.sql.LotXCycle;

/**
 *
 * @author usuario
 */
public class JFPrincipal extends javax.swing.JFrame {

    
    DefaultComboBoxModel modelLot;
    
    /**
     * Creates new form JFLogin
     */
    public JFPrincipal() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/view/source/favicon.ico")).getImage());
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno = new ImageIcon(this.getClass().getResource("/view/source/fondo.jpg"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());        
    }
    
    public void getLots() throws SQLException {
        this.modelLot = new DefaultComboBoxModel();
        this.modelLot.addElement("");
        ArrayList<String> lotsxcycle = Lot.getInstance().getLots(1);
        for (String lotxcycle : lotsxcycle) {
            this.modelLot.addElement(lotxcycle);
        }
        this.jCBLot.setModel(modelLot);
    }    
    public void getCycle() throws SQLException {
         this.modelLot = new DefaultComboBoxModel();
        this.modelLot.addElement("");
        ArrayList<String> lotsxcycle = Cycle.getInstance().getCycle(jCBLot.getSelectedItem().toString());
        for (String lotxcycle : lotsxcycle) {
            this.modelLot.addElement(lotxcycle);
        }
        this.jCBIDCycle.setModel(modelLot);
    }   
    public void getCycles() throws SQLException {
        this.modelLot = new DefaultComboBoxModel();
        this.modelLot.addElement("");
        ArrayList<String> lotsxcycle = Cycle.getInstance().getCycles(jCBIDCycle.getSelectedItem().toString());
        for (String lotxcycle : lotsxcycle) {
            this.modelLot.addElement(lotxcycle);
        }
        this.jTextStart.setText((String) modelLot.getElementAt(1));
    }   
    public void getCycles2() throws SQLException {
        this.modelLot = new DefaultComboBoxModel();
        this.modelLot.addElement("");
        ArrayList<String> lotsxcycle = Cycle.getInstance().getCycles2(jCBIDCycle.getSelectedItem().toString());
        for (String lotxcycle : lotsxcycle) {
            this.modelLot.addElement(lotxcycle);
        }
        this.jTextEnd.setText((String) modelLot.getElementAt(1));
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnRegistrarNotas2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BtnEntrar = new javax.swing.JButton();
        jBtnDiseñar = new javax.swing.JButton();
        jBtnRegistrar = new javax.swing.JButton();
        BtnLoad = new javax.swing.JButton();
        jCBLot = new javax.swing.JComboBox();
        BtnLoadCycles = new javax.swing.JButton();
        jCBIDCycle = new javax.swing.JComboBox();
        BtnLoadDates = new javax.swing.JButton();
        jTextStart = new javax.swing.JTextField();
        jTextEnd = new javax.swing.JTextField();

        jBtnRegistrarNotas2.setText("Registrar Notas");
        jBtnRegistrarNotas2.setEnabled(false);
        jBtnRegistrarNotas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegistrarNotas2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal - Agricultural Property- ");
        setResizable(false);

        BtnEntrar.setText("Acceder");
        BtnEntrar.setEnabled(false);
        BtnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEntrarActionPerformed(evt);
            }
        });

        jBtnDiseñar.setText("Editar Solicitudes");
        jBtnDiseñar.setEnabled(false);
        jBtnDiseñar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDiseñarActionPerformed(evt);
            }
        });

        jBtnRegistrar.setText("Aprobar Solicitudes");
        jBtnRegistrar.setEnabled(false);
        jBtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegistrarActionPerformed(evt);
            }
        });

        BtnLoad.setText("Load");
        BtnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoadActionPerformed(evt);
            }
        });

        jCBLot.setEnabled(false);
        jCBLot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBLotActionPerformed(evt);
            }
        });

        BtnLoadCycles.setText("Load");
        BtnLoadCycles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoadCyclesActionPerformed(evt);
            }
        });

        jCBIDCycle.setEnabled(false);
        jCBIDCycle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBIDCycleActionPerformed(evt);
            }
        });

        BtnLoadDates.setText("Load");
        BtnLoadDates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoadDatesActionPerformed(evt);
            }
        });

        jTextStart.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextStart.setEnabled(false);

        jTextEnd.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextEnd.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jCBLot, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBIDCycle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BtnEntrar)
                                .addGap(73, 73, 73))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(BtnLoad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnLoadCycles)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(jTextStart, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnLoadDates)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jBtnRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnDiseñar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBLot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBIDCycle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3))
                    .addComponent(BtnLoad)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnLoadCycles)
                            .addComponent(jTextEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnLoadDates))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(BtnEntrar)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnRegistrar)
                    .addComponent(jBtnDiseñar))
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEntrarActionPerformed
        String Lots = jCBLot.getSelectedItem().toString();
        String Cycle = jCBIDCycle.getSelectedItem().toString();
        
        try {
            // Se evaluan el usuario y la clave ingresados con el procedimiento Login de la base de datos.
            if (LotXCycle.getInstance().validate(Lots,Cycle)) {
                //cargarGrupos(usuario);
                this.jBtnDiseñar.setEnabled(true);  
                this.jBtnRegistrar.setEnabled(true);  
            } 
            else {
                JOptionPane.showMessageDialog(rootPane, "Los datos no concuerdan");
                System.out.println(Lots);
                System.out.println(Cycle);
            }
        } catch (SQLException ex) {
            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnEntrarActionPerformed


    private void jBtnDiseñarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDiseñarActionPerformed
         // Se valida que se escoja un grupo y que este grupo tenga evaluaciones registradas para poder asi registar su nota. 
            this.setVisible(false);
            JDlgModify modify = new JDlgModify(null, true);
            modify.setLotCode(jCBLot.getSelectedItem().toString());
            modify.setCycleCode(jCBIDCycle.getSelectedItem().toString());
        try {
            modify.getDescrip();
            
        } catch (SQLException ex) {
            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
            modify.setLocationRelativeTo(null);
            modify.setVisible(true);
            this.setVisible(true);
            this.jBtnDiseñar.setEnabled(false);  
            this.jBtnRegistrar.setEnabled(false);
                                     
    }//GEN-LAST:event_jBtnDiseñarActionPerformed

    private void jBtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegistrarActionPerformed
        // Se valida que se escoja un grupo y que este grupo tenga evaluaciones registradas para poder asi registar su nota. 
            this.setVisible(false);
            JDlgApprove registro = new JDlgApprove(null, true);
            registro.setLotCode(jCBLot.getSelectedItem().toString());
            registro.setCycleCode(jCBIDCycle.getSelectedItem().toString());
        try {
            registro.getDescrip();
        } catch (SQLException ex) {
            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
            registro.setLocationRelativeTo(null);
            registro.setVisible(true);
            this.setVisible(true);
            this.jBtnDiseñar.setEnabled(false);  
            this.jBtnRegistrar.setEnabled(false);
    }//GEN-LAST:event_jBtnRegistrarActionPerformed

    private void jBtnRegistrarNotas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegistrarNotas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnRegistrarNotas2ActionPerformed

    private void BtnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoadActionPerformed
        // Se valida que se escoja un grupo y que este grupo tenga evaluaciones registradas para poder asi registar su nota. 
        jCBLot.setEnabled(true);
        try {
            getLots();
        } catch (SQLException ex) {
            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_BtnLoadActionPerformed

    private void jCBLotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBLotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBLotActionPerformed

    private void BtnLoadCyclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoadCyclesActionPerformed
        // Se valida que se escoja un grupo y que este grupo tenga evaluaciones registradas para poder asi registar su nota. 
        jCBIDCycle.setEnabled(true);
        
        try {
            getCycle();
        } catch (SQLException ex) {
            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnLoadCyclesActionPerformed

    private void jCBIDCycleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBIDCycleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBIDCycleActionPerformed

    private void BtnLoadDatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoadDatesActionPerformed

        try {
            getCycles();
            getCycles2();
            BtnEntrar.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }//GEN-LAST:event_BtnLoadDatesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnEntrar;
    public javax.swing.JButton BtnLoad;
    public javax.swing.JButton BtnLoadCycles;
    public javax.swing.JButton BtnLoadDates;
    private javax.swing.JButton jBtnDiseñar;
    private javax.swing.JButton jBtnRegistrar;
    private javax.swing.JButton jBtnRegistrarNotas2;
    private javax.swing.JComboBox jCBIDCycle;
    private javax.swing.JComboBox jCBLot;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextEnd;
    private javax.swing.JTextField jTextStart;
    // End of variables declaration//GEN-END:variables
}
